### ISSUE TITLE
Give eslint-plugin-gusto some love.

### ISSUE THREAD

**Issue by wheeler** [Gusto/eslint-plugin-gusto#9]
Since I'm adding a rule to this package I figured I'd revive it a little. I synced with @bbuchalter and here are a list of things we came up with that would be good to do. I've added some more things too.

Basics:
- [ ] Add LICENSE file
- [ ] Add a CLA
- [x] Create CHANGELOG.md
- [ ] Update readme to express intent to use Semver

Code:
- [x] ignore `/lib` #3 
- [x] checkin `yarn.lock` #4 
- [x] Update `mocha` dev-dependency to resolve Github's Dependency Security Notices #6 
- [x] Update `eslint` dev-dependency to resolve Github's Dependency Security Notice #5 + #11 
- [x] Update `babel` dev-dependencies to resolve Github's Dependency Security Notice
- [x] Get CI to run in travis  #8 + https://github.com/Gusto/eslint-plugin-gusto/commit/d4340d16c08e107fb6833e13cd3e8af87a2b6e2f + https://github.com/Gusto/eslint-plugin-gusto/commit/05441aa34d73b898f935c98d7b803c2622f131b9
- [x] Remove old solano configs
- [x] Add `eslint` step to CI #10
- [x] Enable dependabot once major versions have been updated
- [ ] Re-write rules in non-deprecated format (see note at top of https://eslint.org/docs/developer-guide/working-with-rules)
- [x] ~unpublish/deprecate betas?~ they're already deprecated and can't be unpublished because of that
- [ ] figure out good steps for packing or linking so betas aren't necessary
- [ ] consider using [📦🚀 semantic-release](https://github.com/semantic-release/semantic-release) for automated releasing, tagging, changelogs etc.

Docs:
- [ ] Update code/examples/docs to be less gusto-specific
- [ ] Refactor docs into individual docs per rule rather than all in the main README
- [ ] Describe how to get started with contributing in the Readme
- [ ] Documentation + CI automation for how to publish a new version
